#cloud-config
users:
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/kali
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6TmcJILkt13yT/h9LzJYojOCV41Ggi3rNv6XlpxcBQNN14sRRUWRCVfJfVY2GGn+fbVGSyg5SDpprteAM1xBH+KkrYMvUO0WJLMGAhQOqbfyxp/DXZVygBlRdzEwqiJoSKxm5xjPeQpJM9l5ytnnGR+YCr5T1zDwf1UA9AIU7ibQWx+mP8YcDgt3DBfK1e89XvG3VntTiILzeTsff50PfRys9167YRtOEx6REsq/5rM+qezQ9Gcbrz3dy9PABgDTdIK+5fdziwMGYzAfHpiofM5CIzEoevtfO7auCMfxn9yh772nYtcO/G6u8q/5V6eIphqYDcVbtGqsPiad8lXxZ root@localhost.localdomain
ssh_pwauth: True
disable_root: false
chpasswd:
  list: |
     root: iamroot
     kali:kali
  expire: False
package_update: true
package_upgrade: true
packages:
    - qemu-guest-agent
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - zsh
growpart:
  mode: auto
  devices: ['/']
runcmd:
  - [ sh, -c, 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -' ]
  - [ sh, -c, 'sudo apt-key fingerprint 0EBFCD88']
  - [ sh, -c, 'sudo apt update' ]
  - [ sh, -c, 'mkdir ~/Desktop/utils']
  - [ sh, -c, 'sudo mount -t 9p -o trans=virtio,version=9p2000.L,rw tmp ~/Desktop/utils']
